import Link from 'next/link'
import './globals.css'
import { Control } from './Control'

export const metadata = {
  title: "Juhee Choi's Web Tutorials",
  description: 'Generated by Juhee Choi',
}

export default async function RootLayout({ children }) {
    // fetch('http://localhost:9999/topics')
    //   .then(res=>res.json())
    //   .then(result=>{
    //     setTopics(result)
    // });

    // 위의 fetch처럼 비동기로 처리하지 않고
    // 아래처럼 동기적인 코드로 변경
    const response = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics/', {cache:'no-cache'}) 
    const topics = await response.json();
  return (
    <html>
      <body>
          <h1>
            <a href="/">WEB</a>
          </h1>
          <ol>
            {topics.map((topic)=>{
              return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            })}
            
          </ol>
          {children}
          <Control></Control>
        </body>
    </html>
  )
}
